version: "3.9"

volumes:
  pgdata:

x-postgres-envs: &postgres-envs
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_PORT: ${POSTGRES_PORT}

services:
  postgres:
    image: postgres:latest
    restart: always
    environment: *postgres-envs
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  tracker:
    build:
      context: .
      dockerfile: ./services/tracker/Dockerfile
    environment:
      <<: *postgres-envs
      ETHERSCAN_TOKEN: ${ETHERSCAN_TOKEN}
    depends_on:
      - postgres

  server:
    build:
      context: .
      dockerfile: ./services/server/Dockerfile
    environment: *postgres-envs
    ports:
      - 8000:8000
    depends_on:
      - postgres
