version: "3.9"
services:
  postgres:
    image: postgres:latest
    command: postgres -c 'max_connections=${MAX_CONNECTIONS}'
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ${PGDATA}:/var/lib/postgresql/data
